# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-06 15:15
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.metadata.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20151026_1529'),
        ('releases', '0006_release_checksums'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='instruments',
            field=djangoplicity.metadata.translation.fields.TranslationInstrumentManyToManyField(blank=True, help_text='Instrument used to collect the data. One Instrument entry per exposure.', to='metadata.Instrument', verbose_name='Instrument'),
        ),
    ]
