# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0007_release_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='principal_investigator',
            field=models.CharField(blank=True, help_text='Name of the principal investigator', max_length=255, null=True),
        ),
    ]
