# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-29 16:12
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20220323_1648'),
        ('releases', '0008_release_principal_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='programs',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, to='metadata.Program'),
        ),
    ]
