# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_category_logo'),
        ('releases', '0008_release_principal_investigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='web_category',
            field=models.ManyToManyField(blank=True, to='metadata.Category'),
        ),
    ]
