# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20220323_1648'),
        ('releases', '0009_release_web_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='web_category',
        ),
        migrations.AddField(
            model_name='release',
            name='programs',
            field=models.ManyToManyField(blank=True, to='metadata.Program'),
        ),
    ]
