# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20220803_1204'),
        ('releases', '0009_release_programs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='programs',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, limit_choices_to=models.Q(type__name='Releases'), to='metadata.Program'),
        ),
        migrations.AlterField(
            model_name='release',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='releases.release', verbose_name='Translation source'),
        ),
    ]
