# Generated by Django 3.1 on 2024-10-09 10:01

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_programlogolineup'),
        ('releases', '0011_auto_20230802_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='program_logo_lineup',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.programlogolineup'),
        ),
    ]
