# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 11:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
