# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-23 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20160408_1106'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='menuitem',
            managers=[
            ],
        ),
    ]
