# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-07 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20190926_1400'),
        ('menus', '0003_auto_20190923_1554'),
    ]

    operations = [
    ]
