# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import djangoplicity.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-priority', '-id']},
        ),
        migrations.AlterField(
            model_name='conference',
            name='account_no',
            field=models.CharField(blank=True, help_text=djangoplicity.products.models.DEFAULT_CONFERENCE_ACCOUNT_NO_FUNC, max_length=10),
        ),
        migrations.AlterField(
            model_name='conference',
            name='job',
            field=models.CharField(blank=True, help_text=djangoplicity.products.models.DEFAULT_CONFERENCE_JOB_NO_HELP_TEXT_FUNC, max_length=4),
        ),
        migrations.AlterField(
            model_name='conference',
            name='jsp',
            field=models.IntegerField(blank=True, help_text=djangoplicity.products.models.DEFAULT_CONFERENCE_JSP_NO_FUNC, null=True, verbose_name='JSP'),
        ),
    ]
