# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20150227_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualreport',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='annualreport',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='annualreport',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='brochure',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='brochure',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='brochure',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='conferenceitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='conferenceitem',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='conferenceitem',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='educationalmaterial',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='media',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='media',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='media',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='mountedimage',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='mountedimage',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='mountedimage',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='postcard',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='reserve_count',
        ),
        migrations.RemoveField(
            model_name='technicaldocument',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='technicaldocument',
            name='low_stock_level',
        ),
        migrations.RemoveField(
            model_name='technicaldocument',
            name='reserve_count',
        ),
    ]
