# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-09 10:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.archives.base
import djangoplicity.archives.contrib.satchmo.models
import djangoplicity.archives.fields
import djangoplicity.metadata.archives.fields
import djangoplicity.products.base.consts


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170203_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupernovaActivity',
            fields=[
                ('sale', models.BooleanField(default=False, help_text='For sale - note weight must be provided if product is for sale.')),
                ('price', models.DecimalField(decimal_places=2, default=b'0.00', help_text='Price (EUR)', max_digits=8)),
                ('job', models.CharField(blank=True, help_text=djangoplicity.archives.contrib.satchmo.models.DEFAULT_JOB_NO_HELP_TEXT_FUNC, max_length=4)),
                ('jsp', models.IntegerField(blank=True, help_text=djangoplicity.archives.contrib.satchmo.models.DEFAULT_JSP_NO_FUNC, null=True, verbose_name='JSP')),
                ('account_no', models.CharField(blank=True, help_text=djangoplicity.archives.contrib.satchmo.models.DEFAULT_ACCOUNT_NO_FUNC, max_length=10)),
                ('free', models.BooleanField(default=False, help_text='Available for free.', verbose_name=b'Free')),
                ('shippable', models.BooleanField(default=True, help_text='Calculate shipping for this item.')),
                ('id', djangoplicity.archives.fields.IdField(help_text='Ids are only allowed to contain letters, numbers, underscores or hyphens. They are used in URLs for the archive item.', primary_key=True, serialize=False)),
                ('title', djangoplicity.archives.fields.TitleField(db_index=True, help_text='Title is shown in browser window. Use a good informative title, since search engines normally display the title on their result pages.', max_length=200)),
                ('description', djangoplicity.archives.fields.DescriptionField(blank=True, help_text='')),
                ('priority', djangoplicity.archives.fields.PriorityField(db_index=True, default=0, help_text='Priority of product (100 highest, 0 lowest) - high priority products are ranked higher in search results than low priority products.')),
                ('credit', djangoplicity.metadata.archives.fields.AVMCreditField(blank=True, default=djangoplicity.products.base.consts.DEFAULT_CREDIT_FUNC, help_text='The minimum information that the Publisher would like to see mentioned when the resource is used.', null=False)),
                ('release_date', djangoplicity.archives.fields.ReleaseDateTimeField(blank=True, db_index=True, null=True)),
                ('embargo_date', djangoplicity.archives.fields.ReleaseDateTimeField(blank=True, db_index=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('release_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('embargo_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('checksums', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'supernova activities',
            },
            bases=(djangoplicity.archives.base.ArchiveModel, models.Model),
        ),
    ]
