# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-30 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_supernovaactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibition',
            options={'ordering': ['title', '-group__priority', 'group_order', '-priority']},
        ),
        migrations.AlterModelOptions(
            name='supernovaactivity',
            options={'verbose_name': 'ESO supernova activity', 'verbose_name_plural': 'ESO supernova activities'},
        ),
        migrations.RemoveField(
            model_name='onlineart',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='onlineartauthor',
            name='title',
        ),
        migrations.AlterField(
            model_name='annualreport',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='book',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='capjournal',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='conferenceitem',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='conferenceposter',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='electronicposter',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='map',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='media',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='mountedimage',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='printedposter',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='scienceinschool',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='stecfnewsletter',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='supernovaactivity',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='technicaldocument',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product'),
        ),
    ]
