# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190130_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-priority', 'id']},
        ),
    ]
