# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191007_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualreport',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='application',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='brochure',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='capjournal',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='conferenceitem',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='conferenceposter',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='educationalmaterial',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='electroniccard',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='electronicposter',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='epublication',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='fitsimage',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='flyer',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='handout',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='imaxfilm',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='kidsdrawing',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='map',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='media',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='minisite',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='mountedimage',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='music',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='onlineart',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='onlineartauthor',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='papermodel',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='planetariumshow',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='presskit',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='printedposter',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='scienceinschool',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='stecfnewsletter',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='supernovaactivity',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='technicaldocument',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='archive_category',
            field=models.ManyToManyField(blank=True, to='products.ArchiveCategory'),
        ),
    ]
