# Release type constants
RELEASE_TYPE_PUBLIC = 'PUBLIC'
RELEASE_TYPE_STAGING = 'STAGING'
RELEASE_TYPE_EMBARGO = 'EMBARGO'

RELEASE_TYPE_CHOICES = [
    (RELEASE_TYPE_PUBLIC, RELEASE_TYPE_PUBLIC),
    (RELEASE_TYPE_STAGING, RELEASE_TYPE_STAGING),
    (RELEASE_TYPE_EMBARGO, RELEASE_TYPE_EMBARGO),
]

RELEASE_TYPES_REQUIRING_AUTH = [RELEASE_TYPE_STAGING, RELEASE_TYPE_EMBARGO]
