# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 15:38
from __future__ import unicode_literals
from __future__ import division

from past.utils import old_div
from django.db import migrations, models

def forwards(apps, schema_editor):
    Image = apps.get_model('media', 'Image')
    for i in Image.objects.all():
        if not i.fov_x and not i.fov_y:
            continue

        if i.fov_x:
            fov_x = old_div(i.fov_x, 2)
            i.fov_x_l = -fov_x
            i.fov_x_r = fov_x

        if i.fov_y:
            if i.fov_y == 180 or i.fov_y <= 90:
                fov_y = old_div(i.fov_y, 2)
                i.fov_y_u = fov_y
                i.fov_y_d = -fov_y
            else:
                i.fov_y_u = 90
                i.fov_y_d = -i.fov_y + 90

        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_auto_20170203_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fov_x_l',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Horizontal Field of View (left), in degrees', max_digits=5, null=True, verbose_name=b'FOV x (left)'),
        ),
        migrations.AddField(
            model_name='image',
            name='fov_x_r',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Horizontal Field of View (right), in degrees', max_digits=5, null=True, verbose_name=b'FOV x (right)'),
        ),
        migrations.AddField(
            model_name='image',
            name='fov_y_d',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Vertical Field of View (down), in degrees', max_digits=5, null=True, verbose_name=b'FOV y (down)'),
        ),
        migrations.AddField(
            model_name='image',
            name='fov_y_u',
            field=models.DecimalField(blank=True, decimal_places=2, help_text=b'Vertical Field of View (up), in degrees', max_digits=5, null=True, verbose_name=b'FOV y (up)'),
        ),
        migrations.RunPython(forwards),
    ]
