# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-02-27 10:59
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_video_frame_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='spatial_scale',
            field=djangoplicity.metadata.archives.fields.AVMSpatialScaleField(blank=True, help_text='Spatial scale of the image in number of degrees/pixel (2 element list).', max_length=80, null=True, verbose_name='Scale'),
        ),
    ]
