# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 10:38
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_auto_20180227_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file_type',
            field=djangoplicity.metadata.archives.fields.AVMFileType(blank=True, choices=((b'TIFF', b'TIFF'), (b'JPEG', b'JPEG'), (b'PNG', b'PNG'), (b'GIF', b'GIF'), (b'PSB', b'PSB'), (b'PSD', b'PSD'), (b'PDF', b'PDF')), help_text='The format of the file. For images this would include TIFF, JPEG, PNG, GIF, PSD, PDF.', max_length=4, null=True, verbose_name='File Type'),
        ),
    ]
