# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0025_auto_20181218_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='frame_rate',
            field=models.PositiveIntegerField(default=25),
        ),
    ]
