# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import djangoplicity.media.consts
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_auto_20200629_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=djangoplicity.metadata.archives.fields.AVMTypeField(blank=True, choices=((b'Observation', 'Observation'), (b'Artwork', 'Artwork'), (b'Photographic', 'Photographic'), (b'Planetary', 'Planetary'), (b'Simulation', 'Simulation'), (b'Collage', 'Collage'), (b'Chart', 'Chart')), help_text='The type of image/media resource.', max_length=30, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='video',
            name='frame_rate',
            field=models.PositiveIntegerField(default=djangoplicity.media.consts.DEFAULT_VIDEOS_FRAME_RATE_FUNC),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=djangoplicity.metadata.archives.fields.AVMTypeField(blank=True, choices=((b'Observation', 'Observation'), (b'Artwork', 'Artwork'), (b'Photographic', 'Photographic'), (b'Planetary', 'Planetary'), (b'Simulation', 'Simulation'), (b'Collage', 'Collage'), (b'Chart', 'Chart')), help_text='The type of image/media resource.', max_length=30, null=True, verbose_name='Type'),
        ),
    ]
