# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2021-05-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_auto_20200629_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='giphy_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
