# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 18:48
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.metadata.archives.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_auto_20151026_1529'),
        ('media', '0028_auto_20201029_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='proposal',
            field=djangoplicity.metadata.archives.fields.AVMProposalIDField(blank=True, help_text=b'', to='metadata.ObservationProposal', verbose_name='Observation Proposal/Program ID'),
        ),
        migrations.AddField(
            model_name='image',
            name='publication',
            field=djangoplicity.metadata.archives.fields.AVMPublicationField(blank=True, help_text='ADS Bibliographic Code', to='metadata.Publication', verbose_name='Publication'),
        ),
    ]
