# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-29 16:12
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0029_auto_20211116_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='web_category',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, to='metadata.Category'),
        ),
    ]
