# Generated by Django 3.1 on 2024-01-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0032_auto_20220803_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobroadcastaudiotrack',
            name='type',
            field=models.CharField(choices=[('stereo', 'Stereo soundtrack'), ('split_stereo', 'Split stereo'), ('surround', 'Surround 5.1'), ('split_surround', 'Split surround 5.1'), ('712surround', '7.1.2 Surround'), ('audio_description', 'Audio Description')], max_length=25, verbose_name='Audio track type'),
        ),
    ]
