# Generated by Django 3.1 on 2024-10-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0033_auto_20240117_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='constellation',
            field=models.CharField(blank=True, help_text='Constellation calculated from the spatial_reference_value', max_length=255, null=True),
        ),
    ]
