# Generated by Django 3.1 on 2026-09-17 11:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import djangoplicity.archives.base
import djangoplicity.archives.fields
import djangoplicity.archives.translation
import djangoplicity.metadata.archives.fields
import djangoplicity.translation.fields
import djangoplicity.translation.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0034_image_constellation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiwavelengthImage',
            fields=[
                ('lang', djangoplicity.translation.fields.LanguageField(db_index=True, default=djangoplicity.translation.models._get_defaut_lang, max_length=7, verbose_name='Language')),
                ('translation_ready', models.BooleanField(default=False, help_text='When you check this box and save this translation, an automatic notification email will be sent.')),
                ('id', djangoplicity.archives.fields.IdField(help_text='Ids are only allowed to contain letters, numbers, underscores or hyphens. They are used in URLs for the archive item.', primary_key=True, serialize=False)),
                ('title', djangoplicity.archives.fields.TitleField(db_index=True, help_text='Title is shown in browser window. Use a good informative title, since search engines normally display the title on their result pages.', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', djangoplicity.archives.fields.DescriptionField(blank=True, help_text='')),
                ('credit', djangoplicity.metadata.archives.fields.AVMCreditField(blank=True, help_text='The minimum information that the Publisher would like to see mentioned when the resource is used.', null=False)),
                ('priority', djangoplicity.archives.fields.PriorityField(db_index=True, default=0, help_text='Priority of product (100 highest, 0 lowest) - high priority products are ranked higher in search results than low priority products.')),
                ('main_band', models.CharField(choices=[('gamma-ray', 'Gamma-ray'), ('x-ray', 'X-ray'), ('ultraviolet', 'Ultraviolet'), ('visible', 'Visible light'), ('infrared', 'Infrared'), ('microwave', 'Microwave'), ('radio', 'Radio')], default='visible', help_text='Band shown when the page opens and used as the main visual of the object', max_length=16, verbose_name='Main band')),
                ('release_date', djangoplicity.archives.fields.ReleaseDateTimeField(blank=True, db_index=True, null=True)),
                ('embargo_date', djangoplicity.archives.fields.ReleaseDateTimeField(blank=True, db_index=True, null=True)),
                ('published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('release_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('embargo_task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('checksums', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source', djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='media.multiwavelengthimage', verbose_name='Translation source')),
            ],
            options={
                'verbose_name': 'Multiwavelength Image',
                'ordering': ['-priority', '-release_date'],
                'permissions': [('view_only_non_default', 'Can view only non default language')],
            },
            bases=(djangoplicity.archives.base.ArchiveModel, models.Model),
        ),
        migrations.CreateModel(
            name='MultiwavelengthImageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Multiwavelength Image translation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('media.multiwavelengthimage', djangoplicity.archives.translation.TranslationProxyMixin),
            managers=[
                ('translation_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MultiwavelengthImageBandTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('gamma-ray', 'Gamma-ray'), ('x-ray', 'X-ray'), ('ultraviolet', 'Ultraviolet'), ('visible', 'Visible light'), ('infrared', 'Infrared'), ('microwave', 'Microwave'), ('radio', 'Radio')], db_index=True, max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('translation', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='band_translations', to='media.multiwavelengthimage')),
            ],
            options={
                'verbose_name': 'Wavelength band translation',
                'unique_together': {('translation', 'band')},
            },
        ),
        migrations.CreateModel(
            name='MultiwavelengthImageBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('gamma-ray', 'Gamma-ray'), ('x-ray', 'X-ray'), ('ultraviolet', 'Ultraviolet'), ('visible', 'Visible light'), ('infrared', 'Infrared'), ('microwave', 'Microwave'), ('radio', 'Radio')], db_index=True, max_length=16)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('caption_align', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', help_text='Side of the image where the band text is shown', max_length=5)),
                ('image', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image', verbose_name='Related Image')),
                ('multiwavelength_image', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='media.multiwavelengthimage')),
            ],
            options={
                'verbose_name': 'Wavelength band',
                'unique_together': {('multiwavelength_image', 'band')},
            },
        ),
    ]
