# Generated by Django 3.1 on 2026-09-22 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0035_multiwavelengthimage_multiwavelengthimageband_multiwavelengthimagebandtranslation_multiwavelengthima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiwavelengthimageband',
            options={'ordering': ['wavelength'], 'verbose_name': 'Wavelength band'},
        ),
        migrations.RemoveField(
            model_name='multiwavelengthimage',
            name='main_band',
        ),
        migrations.AddField(
            model_name='multiwavelengthimageband',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Shown when the page opens and used as the main visual of the object. At most one image per object.', verbose_name='Main'),
        ),
        migrations.AddField(
            model_name='multiwavelengthimageband',
            name='wavelength',
            field=models.FloatField(db_index=True, default=550.0, help_text='Wavelength of the observation in nanometres, e.g. 550 for visible light or 1e6 for 1 mm. The band of the spectrum is worked out from it.', validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Wavelength (nm)'),
        ),
        migrations.AlterField(
            model_name='multiwavelengthimagebandtranslation',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media.multiwavelengthimageband', verbose_name='Wavelength band'),
        ),
        migrations.AlterUniqueTogether(
            name='multiwavelengthimageband',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='multiwavelengthimageband',
            constraint=models.UniqueConstraint(condition=models.Q(is_main=True), fields=('multiwavelength_image',), name='media_mwlband_one_main_per_image'),
        ),
        migrations.AddConstraint(
            model_name='multiwavelengthimageband',
            constraint=models.CheckConstraint(check=models.Q(wavelength__gt=0), name='media_mwlband_wavelength_positive'),
        ),
        migrations.RemoveField(
            model_name='multiwavelengthimageband',
            name='band',
        ),
    ]
