# Generated by Django 3.1 on 2026-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0036_mwlband_wavelength_nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiwavelengthimage',
            name='use_wavelength_selector',
            field=models.BooleanField(default=True, help_text='Show the spectrum selector. Untick it to show a simpler image switcher instead.', verbose_name='Wavelength selector'),
        ),
    ]
