# Generated by Django 3.1 on 2026-10-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0037_multiwavelengthimage_use_wavelength_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiwavelengthimage',
            name='constellations_image_url',
            field=models.URLField(blank=True, help_text='Full URL of a transparent PNG with the constellations, in the screen format. Leave it empty if there is none.', max_length=255, verbose_name='Constellations image URL'),
        ),
        migrations.AddField(
            model_name='multiwavelengthimage',
            name='annotations_image_url',
            field=models.URLField(blank=True, help_text='Full URL of a transparent PNG with the annotations, in the screen format. Leave it empty if there is none.', max_length=255, verbose_name='Annotations image URL'),
        ),
    ]
