# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0008_category_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(verbose_name='URL')),
                ('name', models.CharField(help_text='Title of query to be displayed to the user.', max_length=255)),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True, verbose_name=b'Logo URL')),
                ('enabled', models.BooleanField(default=True)),
                ('type', models.ForeignKey(help_text='Defines to which archive this query applies.', on_delete=django.db.models.deletion.CASCADE, to='metadata.CategoryType')),
            ],
            options={
                'ordering': ('type', 'name'),
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('url', 'type')]),
        ),
    ]
