# Generated by Django 3.1 on 2022-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20220323_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='taxonomyhierarchy',
            name='top_level',
            field=models.CharField(choices=[('A', 'Solar System'), ('B', 'Milky Way'), ('C', 'Local Universe'), ('D', 'Early Universe'), ('E', 'Unspecified')], db_index=True, max_length=1, verbose_name='Top Level Hierarchy'),
        ),
    ]
