# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-03 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0009_auto_20220323_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('name',), 'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('url',)]),
        ),
    ]
