# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-03 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0010_auto_20230503_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
        migrations.AddField(
            model_name='program',
            name='types',
            field=models.ManyToManyField(help_text='Defines to which types this program applies.', to='metadata.CategoryType'),
        ),
    ]
