# Generated by Django 3.1 on 2023-08-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20230510_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='type',
        ),
    ]
