# Generated by Django 3.1 on 2023-12-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0012_remove_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='related_programs',
            field=models.ManyToManyField(blank=True, related_name='_program_related_programs_+', to='metadata.Program', verbose_name='Join with Programs'),
        ),
    ]
