# Generated by Django 3.1 on 2023-12-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0013_program_related_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='join_in_browser',
            field=models.CharField(blank=True, help_text='Add the type of views where you want to merge the programs', max_length=255, null=True),
        ),
    ]
