# Generated by Django 3.1 on 2024-10-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0014_program_join_in_browser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLogoLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the logo line-up', max_length=255)),
                ('logo_lineup_url', models.URLField(verbose_name='Logo line-up URL')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.program')),
            ],
            options={
                'verbose_name': 'Program Logo Lineup',
                'verbose_name_plural': 'Programs Logo Lineups',
                'ordering': ('name',),
            },
        ),
    ]
