  version: '3'

  services:
    db:
      image: postgres:10.5
      container_name: djangoplicity-db
      restart: always
      environment:
        POSTGRES_DB: djangoplicity
        POSTGRES_USER: djangoplicity
        POSTGRES_PASSWORD: djangoplicity
      ports:
        - "50001:5432"

    web:
      build: .
      container_name: djangoplicity-web
      command: ["./scripts/command-dev.sh"]
      volumes:
      - ./djangoplicity:/app/djangoplicity
      - ./tests:/app/tests
      ports:
        - "8001:8000"
      depends_on:
        - db