  version: '3'

  services:
    db:
      image: mysql
      container_name: djangoplicity-db
      environment:
        - MYSQL_DATABASE='db'
        - MYSQL_USER='mysql'
        - MYSQL_PASSWORD='mysql'
        - MYSQL_ROOT_PASSWORD='mysql'

    web:
      build: .
      container_name: djangoplicity-web
      command: python manage.py runserver 0.0.0.0:8001
      volumes:
      - ./djangoplicity:/home/djangoplicityadm/djangoplicity
      ports:
        - "8001:8001"
      depends_on:
        - db