# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_video_frame_rate'),
        ('announcements', '0005_auto_20170203_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementImageComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('main_visual', models.BooleanField(default=False)),
                ('override_id', models.SlugField(blank=True, null=True, verbose_name='Override ID')),
                ('hide', models.BooleanField(default=False, verbose_name='Hide on kiosk')),
                ('announcement', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.Announcement', verbose_name='Related announcement')),
                ('archive_item', djangoplicity.translation.fields.TranslationForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.ImageComparison', verbose_name='Related Image Comparison')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='related_comparisons',
            field=djangoplicity.translation.fields.TranslationManyToManyField(through='announcements.AnnouncementImageComparison', to='media.ImageComparison'),
        ),
    ]
