# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-05-03 09:21
from __future__ import unicode_literals

from django.db import migrations
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20230503_0539'),
        ('announcements', '0006_auto_20180126_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='programs',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, to='metadata.Program'),
        ),
    ]
