# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_auto_20180126_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='announcements.announcement', verbose_name='Translation source'),
        ),
    ]
