# Generated by Django 3.1 on 2023-05-10 15:39

from django.db import migrations, models
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0011_auto_20230510_1539'),
        ('announcements', '0007_auto_20220912_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='programs',
            field=djangoplicity.translation.fields.TranslationManyToManyField(blank=True, limit_choices_to=models.Q(types__name__iexact='Announcements'), to='metadata.Program'),
        ),
    ]
