# Generated by Django 3.1 on 2024-10-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_announcement_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_e_and_e',
            field=models.BooleanField(default=False, help_text='Check this if the announcement is for the special E&E category and newsletter', verbose_name='Is E&E'),
        ),
    ]
