# Generated by Django 3.1 on 2025-07-22 13:53

from django.db import migrations
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0015_programlogolineup'),
        ('announcements', '0009_announcement_is_e_and_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='program_logo_lineup',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.programlogolineup'),
        ),
    ]
