# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_page_context_processors'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='live_edit',
            field=models.BooleanField(default=True, help_text="Allow Live edit (only if the page doesn't use javascript, embed, etc.)"),
        ),
    ]
