# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-23 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_live_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='opengraph_image',
            field=models.CharField(blank=True, help_text="Example: 'https://www.eso.org/public/archives/imagecomparisons/newsfeature/potw1413a.jpg'. If given: full path to an image that will be used when sharing the page on social media. Must be larger than 200x200px and smaller than 5MB.", max_length=250, verbose_name='OpenGraph Image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_url',
            field=models.CharField(blank=True, db_index=True, help_text="Example: 'https://www.eso.org/public/'. Used if the page has been permanently moved. If given, access to the page will trigger a HTTP 301 redirection to the given URL.", max_length=200, verbose_name='Redirect URL'),
        ),
    ]
