# Generated by Django 3.1 on 2022-09-12 10:22

from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.translation.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191029_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedpagekey',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select page that you want to use for the specific key. Note, only pages marked as embedded pages can be selected.', limit_choices_to={'embedded__exact': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='script',
            field=models.TextField(blank=True, help_text='Javascript to be included in page footer'),
        ),
        migrations.AlterField(
            model_name='page',
            name='source',
            field=djangoplicity.translation.fields.TranslationForeignKey(blank=True, limit_choices_to={'source__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, only_sources=False, related_name='translations', to='pages.page', verbose_name='Translation source'),
        ),
    ]
