# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeorder',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[(b'NOSTOCK', b'The product(s) is/are not available on stock.'), (b'UNQUALIFIED', b'You did not qualify for receiving free orders at this occasion.'), (b'INSUFFICIENT', b'Your justification is not sufficient to evaluate the request.'), (b'AMOUNT', b'Your order was above our maximum of 180 EUR.'), (b'OLDCUSTOMER', b'You already received a free order during the last six months'), (b'ESONONLY', b'Unfortunately we no longer ship free orders outside ESO Member States and host country Chile: https://www.eso.org/public/about-eso/memberstates/'), (b'EUROONLY', b'Unfortunately we no longer ship free orders outside Europe.'), (b'BUSY', b'Due to an increase in demand, we were not able to accept your request at this time.')], max_length=255),
        ),
    ]
