# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-07 16:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0003_auto_20151029_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceannouncement',
            name='checksums',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
