# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglists', '0002_auto_20151028_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailchimpmergevar',
            options={'ordering': ['list', 'name'], 'verbose_name': 'mailchimp merge field'},
        ),
        migrations.AlterModelOptions(
            name='mergevarmapping',
            options={'verbose_name': 'mailchimp merge field mapping'},
        ),
        migrations.RemoveField(
            model_name='mailchimplist',
            name='use_awesomebar',
        ),
        migrations.AddField(
            model_name='mailchimpgrouping',
            name='interest_id',
            field=models.CharField(db_index=True, default='dummy', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailchimpgroup',
            name='group_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mailchimpgrouping',
            name='group_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mailchimplist',
            name='primary_key_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailinglists.MailChimpMergeVar'),
        ),
    ]
