# Generated by Django 3.1 on 2025-08-03 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangoplicity.contentserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentServerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text='The archive format (e.g. original, thumbs, screen, ultra_hd)', max_length=30)),
                ('extension', models.CharField(blank=True, help_text='File extension (e.g., .tif, .png, .mp4)', max_length=20)),
                ('resource_size', models.BigIntegerField(help_text='Resource size in bytes', validators=[django.core.validators.MinValueValidator(0)])),
                ('checksum', models.CharField(blank=True, help_text='Resource checksum (MD5/SHA256)', max_length=128, null=True)),
                ('content_server', djangoplicity.contentserver.models.ContentServerField(blank=True, default=djangoplicity.contentserver.models._get_default_content_server, max_length=255)),
                ('content_server_path', models.CharField(help_text='Full path on content server', max_length=500)),
                ('object_id', models.SlugField()),
                ('is_directory', models.BooleanField(default=False, help_text='Whether this resource is a directory')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the resource is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(blank=True, help_text='When the resource was uploaded', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Server Resource',
                'verbose_name_plural': 'Content Server Resources',
            },
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['content_type', 'object_id'], name='contentserv_content_e61ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['format'], name='contentserv_format_54782b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['is_directory'], name='contentserv_is_dire_54a01d_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['is_active'], name='contentserv_is_acti_dd67bc_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['created_at'], name='contentserv_created_ae1450_idx'),
        ),
    ]
