# Generated by Django 3.1 on 2025-08-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentserver', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['content_server_path', 'is_active'], name='contentserv_content_955950_idx'),
        ),
    ]
