# Generated by Django 3.1 on 2026-05-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentserver', '0002_auto_20250806_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentserverresource',
            name='is_public',
            field=models.BooleanField(null=True, blank=True, help_text='Whether this resource is public in the content server, when null it means the privacy is unknown'),
        ),
        migrations.AddIndex(
            model_name='contentserverresource',
            index=models.Index(fields=['is_public'], name='contentserv_is_publ_e32736_idx'),
        ),
    ]
