# This script generates a dummy template files containing all menu entries
# so that they are picked up by makemessage

import codecs
import django

django.setup()
from django.conf import settings

from djangoplicity.menus.models import MenuItem

template_path = settings.PRJBASE + '/templates/menu_strings.html'

f = codecs.open(template_path, 'w', 'utf-8')
f.write('# DO NOT EDIT! This file is automatically generated by djangoplicity/scripts/menu_translations.py\n\n')

for item in MenuItem.objects.all():
    f.write('{%% trans "%s" %%}\n' % item.title)

f.close()
