taxonomy = [
(['1', None, None, None, None],'Planet'),
(['1', '1', None, None, None],'Planet : [Type]'),
(['1', '1', '1', None, None],'Planet : [Type] : Terrestrial'),
(['1', '1', '2', None, None],'Planet : [Type] : Gas Giant'),
(['1', '2', None, None, None],'Planet : [Feature]'),
(['1', '2', '1', None, None],'Planet : [Feature] : Surface'),
(['1', '2', '1', '1', None],'Planet : [Feature] : Surface : Mountain'),
(['1', '2', '1', '2', None],'Planet : [Feature] : Surface : Canyon'),
(['1', '2', '1', '3', None],'Planet : [Feature] : Surface : Volcanic'),
(['1', '2', '1', '4', None],'Planet : [Feature] : Surface : Impact'),
(['1', '2', '1', '5', None],'Planet : [Feature] : Surface : Erosion'),
(['1', '2', '1', '6', None],'Planet : [Feature] : Surface : Liquid'),
(['1', '2', '1', '7', None],'Planet : [Feature] : Surface : Ice'),
(['1', '2', '2', None, None],'Planet : [Feature] : Atmosphere'),
(['1', '2', '2', '1', None],'Planet : [Feature] : Atmosphere : Cloud'),
(['1', '2', '2', '2', None],'Planet : [Feature] : Atmosphere : Storm'),
(['1', '2', '2', '3', None],'Planet : [Feature] : Atmosphere : Belt'),
(['1', '2', '2', '4', None],'Planet : [Feature] : Atmosphere : Aurora'),
(['1', '3', None, None, None],'Planet : [Special Cases]'),
(['1', '3', '1', None, None],'Planet : [Special Cases] : Transiting'),
(['1', '3', '2', None, None],'Planet : [Special Cases] : Hot Jupiter'),
(['1', '3', '3', None, None],'Planet : [Special Cases] : Pulsar planet'),
(['1', '4', None, None, None],'Planet : Satellite'),
(['1', '4', '1', None, None],'Planet : Satellite : [Feature]'),
(['1', '4', '1', '1', None],'Planet : Satellite : [Feature] : Surface'),
(['1', '4', '1', '1', '1'],'Planet : Satellite : [Feature] : Surface : Mountain'),
(['1', '4', '1', '1', '2'],'Planet : Satellite : [Feature] : Surface : Canyon'),
(['1', '4', '1', '1', '3'],'Planet : Satellite : [Feature] : Surface : Volcanic'),
(['1', '4', '1', '1', '4'],'Planet : Satellite : [Feature] : Surface : Impact'),
(['1', '4', '1', '1', '5'],'Planet : Satellite : [Feature] : Surface : Erosion'),
(['1', '4', '1', '1', '6'],'Planet : Satellite : [Feature] : Surface : Liquid'),
(['1', '4', '1', '1', '7'],'Planet : Satellite : [Feature] : Surface : Ice'),
(['1', '4', '1', '2', None],'Planet : Satellite : [Feature] : Atmosphere'),
(['1', '5', None, None, None],'Planet : Ring'),
(['2', None, None, None, None],'Interplanetary Body'),
(['2', '1', None, None, None],'Interplanetary Body : Dwarf planet'),
(['2', '2', None, None, None],'Interplanetary Body : Comet'),
(['2', '2', '1', None, None],'Interplanetary Body : Comet : Nucleus'),
(['2', '2', '2', None, None],'Interplanetary Body : Comet : Coma'),
(['2', '2', '3', None, None],'Interplanetary Body : Comet : Tail'),
(['2', '2', '3', '1', None],'Interplanetary Body : Comet : Tail : Dust'),
(['2', '2', '3', '2', None],'Interplanetary Body : Comet : Tail : Gas'),
(['2', '3', None, None, None],'Interplanetary Body : Asteroid'),
(['2', '4', None, None, None],'Interplanetary Body : Meteoroid'),
(['3', None, None, None, None],'Star'),
(['3', '1', None, None, None],'Star : [Evolutionary Stage]'),
(['3', '1', '1', None, None],'Star : [Evolutionary Stage] : Protostar'),
(['3', '1', '2', None, None],'Star : [Evolutionary Stage] : Young Stellar Object'),
(['3', '1', '3', None, None],'Star : [Evolutionary Stage] : Main Sequence'),
(['3', '1', '4', None, None],'Star : [Evolutionary Stage] : Red Giant'),
(['3', '1', '5', None, None],'Star : [Evolutionary Stage] : Red Supergiant'),
(['3', '1', '6', None, None],'Star : [Evolutionary Stage] : Blue Supergiant'),
(['3', '1', '7', None, None],'Star : [Evolutionary Stage] : White Dwarf'),
(['3', '1', '8', None, None],'Star : [Evolutionary Stage] : Supernova'),
(['3', '1', '9', None, None],'Star : [Evolutionary Stage] : Neutron Star'),
(['3', '1', '9', '1', None],'Star : [Evolutionary Stage] : Neutron Star : Pulsar'),
(['3', '1', '9', '2', None],'Star : [Evolutionary Stage] : Neutron Star : Magnetar'),
(['3', '1', '10', None, None],'Star : [Evolutionary Stage] : Black Hole'),
(['3', '2', None, None, None],'Star : [Type]'),
(['3', '2', '1', None, None],'Star : [Type] : Variable'),
(['3', '2', '1', '1', None],'Star : [Type] : Variable : Pulsating'),
(['3', '2', '1', '2', None],'Star : [Type] : Variable : Irregular'),
(['3', '2', '1', '3', None],'Star : [Type] : Variable : Eclipsing'),
(['3', '2', '1', '4', None],'Star : [Type] : Variable : Flare Star'),
(['3', '2', '1', '5', None],'Star : [Type] : Variable : Nova'),
(['3', '2', '1', '6', None],'Star : [Type] : Variable : X-Ray Binary (Star)'),
(['3', '2', '2', None, None],'Star : [Type] : Carbon'),
(['3', '2', '3', None, None],'Star : [Type] : Brown Dwarf'),
(['3', '2', '4', None, None],'Star : [Type] : Wolf-Rayet'),
(['3', '2', '5', None, None],'Star : [Type] : Blue Straggler'),
(['3', '2', '6', None, None],'Star : [Type] : Exotic'),
(['3', '2', '6', '1', None],'Star : [Type] : Exotic : X-Ray Binary'),
(['3', '3', None, None, None],'Star : [Spectral Type]'),
(['3', '3', '1', None, None],'Star : [Spectral Type] : O'),
(['3', '3', '2', None, None],'Star : [Spectral Type] : B'),
(['3', '3', '3', None, None],'Star : [Spectral Type] : A'),
(['3', '3', '4', None, None],'Star : [Spectral Type] : F'),
(['3', '3', '5', None, None],'Star : [Spectral Type] : G'),
(['3', '3', '6', None, None],'Star : [Spectral Type] : K'),
(['3', '3', '7', None, None],'Star : [Spectral Type] : M'),
(['3', '3', '8', None, None],'Star : [Spectral Type] : L'),
(['3', '3', '9', None, None],'Star : [Spectral Type] : T'),
(['3', '4', None, None, None],'Star : [Population]'),
(['3', '4', '1', None, None],'Star : [Population] : I'),
(['3', '4', '2', None, None],'Star : [Population] : II'),
(['3', '4', '3', None, None],'Star : [Population] : III'),
(['3', '5', None, None, None],'Star : [Feature]'),
(['3', '5', '1', None, None],'Star : [Feature] : Photosphere'),
(['3', '5', '1', '1', None],'Star : [Feature] : Photosphere : Granulation'),
(['3', '5', '1', '2', None],'Star : [Feature] : Photosphere : Sunspot'),
(['3', '5', '2', None, None],'Star : [Feature] : Chromosphere'),
(['3', '5', '2', '1', None],'Star : [Feature] : Chromosphere : Flare'),
(['3', '5', '2', '2', None],'Star : [Feature] : Chromosphere : Facula'),
(['3', '5', '3', None, None],'Star : [Feature] : Corona'),
(['3', '5', '3', '1', None],'Star : [Feature] : Corona : Prominence'),
(['3', '6', None, None, None],'Star : [Grouping]'),
(['3', '6', '1', None, None],'Star : [Grouping] : Binary'),
(['3', '6', '2', None, None],'Star : [Grouping] : Triple'),
(['3', '6', '3', None, None],'Star : [Grouping] : Multiple'),
(['3', '6', '4', None, None],'Star : [Grouping] : Cluster'),
(['3', '6', '4', '1', None],'Star : [Grouping] : Cluster : Open'),
(['3', '6', '4', '2', None],'Star : [Grouping] : Cluster : Globular'),
(['3', '7', None, None, None],'Star : Circumstellar Material'),
(['3', '7', '1', None, None],'Star : Circumstellar Material : Planetary System'),
(['3', '7', '2', None, None],'Star : Circumstellar Material : Disk'),
(['3', '7', '2', '1', None],'Star : Circumstellar Material : Disk : Protoplanetary'),
(['3', '7', '2', '2', None],'Star : Circumstellar Material : Disk : Accretion'),
(['3', '7', '2', '3', None],'Star : Circumstellar Material : Disk : Debris'),
(['3', '7', '3', None, None],'Star : Circumstellar Material : Outflow'),
(['3', '7', '3', '1', None],'Star : Circumstellar Material : Outflow : Solar Wind'),
(['3', '7', '3', '2', None],'Star : Circumstellar Material : Outflow : Coronal Mass Ejection'),
(['4', None, None, None, None],'Nebula'),
(['4', '1', None, None, None],'Nebula : [Type]'),
(['4', '1', '1', None, None],'Nebula : [Type] : Interstellar Medium'),
(['4', '1', '2', None, None],'Nebula : [Type] : Star Formation'),
(['4', '1', '3', None, None],'Nebula : [Type] : Planetary'),
(['4', '1', '4', None, None],'Nebula : [Type] : Supernova Remnant'),
(['4', '1', '5', None, None],'Nebula : [Type] : Jet'),
(['4', '2', None, None, None],'Nebula : [Appearance]'),
(['4', '2', '1', None, None],'Nebula : [Appearance] : Emission'),
(['4', '2', '1', '1', None],'Nebula : [Appearance] : Emission : H II Region'),
(['4', '2', '2', None, None],'Nebula : [Appearance] : Reflection'),
(['4', '2', '2', '1', None],'Nebula : [Appearance] : Reflection : Light Echo'),
(['4', '2', '3', None, None],'Nebula : [Appearance] : Dark'),
(['4', '2', '3', '1', None],'Nebula : [Appearance] : Dark : Molecular Cloud'),
(['4', '2', '3', '2', None],'Nebula : [Appearance] : Dark : Bok Globule'),
(['4', '2', '3', '3', None],'Nebula : [Appearance] : Dark : Proplyd'),
(['5', None, None, None, None],'Galaxy'),
(['5', '1', None, None, None],'Galaxy : [Type]'),
(['5', '1', '1', None, None],'Galaxy : [Type] : Spiral'),
(['5', '1', '2', None, None],'Galaxy : [Type] : Barred'),
(['5', '1', '3', None, None],'Galaxy : [Type] : Lenticular'),
(['5', '1', '4', None, None],'Galaxy : [Type] : Elliptical'),
(['5', '1', '5', None, None],'Galaxy : [Type] : Ring'),
(['5', '1', '6', None, None],'Galaxy : [Type] : Irregular'),
(['5', '1', '7', None, None],'Galaxy : [Type] : Interacting'),
(['5', '1', '8', None, None],'Galaxy : [Type] : Gravitationally Lensed'),
(['5', '2', None, None, None],'Galaxy : [Size]'),
(['5', '2', '1', None, None],'Galaxy : [Size] : Giant'),
(['5', '2', '2', None, None],'Galaxy : [Size] : Dwarf'),
(['5', '3', None, None, None],'Galaxy : [Activity]'),
(['5', '3', '1', None, None],'Galaxy : [Activity] : Normal'),
(['5', '3', '2', None, None],'Galaxy : [Activity] : AGN'),
(['5', '3', '2', '1', None],'Galaxy : [Activity] : AGN : Quasar'),
(['5', '3', '2', '2', None],'Galaxy : [Activity] : AGN : Seyfert'),
(['5', '3', '2', '3', None],'Galaxy : [Activity] : AGN : Blazar'),
(['5', '3', '2', '4', None],'Galaxy : [Activity] : AGN : Liner'),
(['5', '3', '3', None, None],'Galaxy : [Activity] : Starburst'),
(['5', '3', '4', None, None],'Galaxy : [Activity] : Ultraluminous'),
(['5', '4', None, None, None],'Galaxy : [Component]'),
(['5', '4', '1', None, None],'Galaxy : [Component] : Bulge'),
(['5', '4', '2', None, None],'Galaxy : [Component] : Bar'),
(['5', '4', '3', None, None],'Galaxy : [Component] : Disk'),
(['5', '4', '4', None, None],'Galaxy : [Component] : Halo'),
(['5', '4', '5', None, None],'Galaxy : [Component] : Ring'),
(['5', '4', '6', None, None],'Galaxy : [Component] : Central Black Hole'),
(['5', '4', '7', None, None],'Galaxy : [Component] : Spiral Arm'),
(['5', '4', '8', None, None],'Galaxy : [Component] : Dust Lane'),
(['5', '4', '9', None, None],'Galaxy : [Component] : Center/Core'),
(['5', '5', None, None, None],'Galaxy : [Grouping]'),
(['5', '5', '1', None, None],'Galaxy : [Grouping] : Pair'),
(['5', '5', '2', None, None],'Galaxy : [Grouping] : Multiple'),
(['5', '5', '3', None, None],'Galaxy : [Grouping] : Cluster'),
(['5', '5', '4', None, None],'Galaxy : [Grouping] : Supercluster'),
(['6', None, None, None, None],'Cosmology'),
(['6', '1', None, None, None],'Cosmology : [Morphology]'),
(['6', '1', '1', None, None],'Cosmology : [Morphology] : Deep Field'),
(['6', '1', '2', None, None],'Cosmology : [Morphology] : Large-Scale Structure'),
(['6', '1', '3', None, None],'Cosmology : [Morphology] : Cosmic Background'),
(['6', '2', None, None, None],'Cosmology : [Phenomenon]'),
(['6', '2', '1', None, None],'Cosmology : [Phenomenon] : Lensing'),
(['6', '2', '2', None, None],'Cosmology : [Phenomenon] : Gamma Ray Burst'),
(['6', '2', '3', None, None],'Cosmology : [Phenomenon] : Dark Matter'),
(['7', None, None, None, None],'Sky Phenomenon'),
(['7', '1', None, None, None],'Sky Phenomenon : Night Sky'),
(['7', '1', '1', None, None],'Sky Phenomenon : Night Sky : Constellation'),
(['7', '1', '2', None, None],'Sky Phenomenon : Night Sky : Asterism'),
(['7', '1', '3', None, None],'Sky Phenomenon : Night Sky : Milky Way'),
(['7', '1', '4', None, None],'Sky Phenomenon : Night Sky : Trail'),
(['7', '1', '4', '1', None],'Sky Phenomenon : Night Sky : Trail : Meteor'),
(['7', '1', '4', '2', None],'Sky Phenomenon : Night Sky : Trail : Star'),
(['7', '1', '4', '3', None],'Sky Phenomenon : Night Sky : Trail : Satellite'),
(['7', '1', '5', None, None],'Sky Phenomenon : Night Sky : Zodiacal Light'),
(['7', '1', '5', '1', None],'Sky Phenomenon : Night Sky : Zodiacal Light : Gegenschein'),
(['7', '1', '6', None, None],'Sky Phenomenon : Night Sky : Night glow'),
(['7', '2', None, None, None],'Sky Phenomenon : Eclipse'),
(['7', '2', '1', None, None],'Sky Phenomenon : Eclipse : Solar'),
(['7', '2', '1', '1', None],'Sky Phenomenon : Eclipse : Solar : Total'),
(['7', '2', '1', '2', None],'Sky Phenomenon : Eclipse : Solar : Partial'),
(['7', '2', '1', '3', None],'Sky Phenomenon : Eclipse : Solar : Annular'),
(['7', '2', '2', None, None],'Sky Phenomenon : Eclipse : Lunar'),
(['7', '2', '2', '1', None],'Sky Phenomenon : Eclipse : Lunar : Total'),
(['7', '2', '2', '2', None],'Sky Phenomenon : Eclipse : Lunar : Partial'),
(['7', '2', '2', '3', None],'Sky Phenomenon : Eclipse : Lunar : Penumbral'),
(['7', '2', '3', None, None],'Sky Phenomenon : Eclipse : Occultation'),
(['7', '2', '4', None, None],'Sky Phenomenon : Eclipse : Transit'),
(['7', '3', None, None, None],'Sky Phenomenon : Light Phenomenon'),
(['7', '3', '1', None, None],'Sky Phenomenon : Light Phenomenon : Sunrise-Sunset'),
(['7', '3', '1', '1', None],'Sky Phenomenon : Light Phenomenon : Sunrise-Sunset : Green flash'),
(['7', '3', '1', '2', None],'Sky Phenomenon : Light Phenomenon : Sunrise-Sunset : Refractive Distortion'),
(['7', '3', '1', '3', None],'Sky Phenomenon : Light Phenomenon : Sunrise-Sunset : Sun Pillar'),
(['7', '3', '2', None, None],'Sky Phenomenon : Light Phenomenon : Cloud'),
(['7', '3', '2', '1', None],'Sky Phenomenon : Light Phenomenon : Cloud : Iridescent'),
(['7', '3', '2', '2', None],'Sky Phenomenon : Light Phenomenon : Cloud : Noctilucent'),
(['7', '3', '2', '3', None],'Sky Phenomenon : Light Phenomenon : Cloud : Nacreous'),
(['7', '3', '2', '4', None],'Sky Phenomenon : Light Phenomenon : Cloud : Corona'),
(['7', '3', '2', '5', None],'Sky Phenomenon : Light Phenomenon : Cloud : Glory'),
(['7', '3', '3', None, None],'Sky Phenomenon : Light Phenomenon : Rainbow'),
(['7', '3', '3', '1', None],'Sky Phenomenon : Light Phenomenon : Rainbow : Moonbow'),
(['7', '3', '3', '2', None],'Sky Phenomenon : Light Phenomenon : Rainbow : Fogbow'),
(['7', '3', '4', None, None],'Sky Phenomenon : Light Phenomenon : Halo'),
(['7', '3', '4', '1', None],'Sky Phenomenon : Light Phenomenon : Halo : Circle'),
(['7', '3', '4', '2', None],'Sky Phenomenon : Light Phenomenon : Halo : Parhelia'),
(['7', '3', '4', '3', None],'Sky Phenomenon : Light Phenomenon : Halo : Arc'),
(['7', '3', '5', None, None],'Sky Phenomenon : Light Phenomenon : Ray-Shadow'),
(['7', '3', '5', '1', None],'Sky Phenomenon : Light Phenomenon : Ray-Shadow : Crepuscular ray'),
(['7', '3', '5', '2', None],'Sky Phenomenon : Light Phenomenon : Ray-Shadow : Anti-crepuscular ray'),
(['7', '3', '5', '3', None],'Sky Phenomenon : Light Phenomenon : Ray-Shadow : Earth shadow'),
(['7', '3', '6', None, None],'Sky Phenomenon : Light Phenomenon : Lightning'),
(['7', '3', '7', None, None],'Sky Phenomenon : Light Phenomenon : Aurora'),
(['8', None, None, None, None],'Technology'),
(['8', '1', None, None, None],'Technology : Observatory'),
(['8', '1', '1', None, None],'Technology : Observatory : Facility'),
(['8', '1', '2', None, None],'Technology : Observatory : Telescope'),
(['8', '1', '3', None, None],'Technology : Observatory : Instrument'),
(['8', '1', '4', None, None],'Technology : Observatory : Detector'),
(['8', '2', None, None, None],'Technology : Spacecraft'),
(['8', '2', '1', None, None],'Technology : Spacecraft : Orbiter'),
(['8', '2', '2', None, None],'Technology : Spacecraft : Probe'),
(['8', '2', '3', None, None],'Technology : Spacecraft : Lander'),
(['8', '2', '4', None, None],'Technology : Spacecraft : Manned'),
(['8', '2', '5', None, None],'Technology : Spacecraft : Launch Vehicle'),
(['9', None, None, None, None],'People'),
(['9', '1', None, None, None],'People : Scientist'),
(['9', '2', None, None, None],'People : Astronaut'),
(['9', '3', None, None, None],'People : Other/General'),
]

from djangoplicity.metadata.models import TaxonomyHierarchy

TaxonomyHierarchy.objects.all().delete()

from djangoplicity.metadata.consts import TOP_LEVEL_HIERARCHY

for tl_code,tl_name in TOP_LEVEL_HIERARCHY:
    if tl_code=='X':
        continue
    
    th = TaxonomyHierarchy( top_level=tl_code, name=tl_name )
    th.save()
    th = None
    
    for code,name in taxonomy:
        # Certain elements doesn't make sense in themselves
        if name.split(" : ").pop()[0] != '[':
            th = TaxonomyHierarchy( top_level=tl_code, level1=code[0], level2=code[1], level3=code[2], level4=code[3], level5=code[4], name=" : ".join( [tl_name, name.replace('[','').replace(']','') ] ) )
            th.save()