# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_auto_20151104_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterFeedDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.BooleanField(default=True, help_text='Return a list of items or a single element')),
                ('name', models.SlugField(help_text='Name used to access this data source in templates')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(verbose_name='URL to the JSON feed')),
                ('limit', models.CharField(blank=True, max_length=255)),
                ('fetch_translations', models.BooleanField(default=True, help_text='Fetch translated version of the feed if available')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletters.NewsletterType')),
            ],
            options={
                'ordering': ('type__name', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='newsletterfeeddatasource',
            unique_together=set([('type', 'name')]),
        ),
    ]
