# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_newsletter_checksums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettertype',
            name='subject_template',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
