# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0009_auto_20170619_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailerlog',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
